include_recipe '../cookbooks/common/default.rb'
include_recipe '../cookbooks/erlang/default.rb'
include_recipe '../cookbooks/elixir/default.rb'
include_recipe '../cookbooks/ruby/default.rb'
include_recipe '../cookbooks/zsh/default.rb'
include_recipe '../cookbooks/nodejs/default.rb'
include_recipe '../cookbooks/dotfiles/default.rb'
